# Generated by Django 4.2.2 on 2023-06-28 15:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='costumer',
            new_name='customer',
        ),
    ]
