# Generated by Django 4.2.2 on 2023-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_costumer_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://pixabay.com/photos/polynesia-french-polynesia-tahiti-3021072/', upload_to=''),
        ),
    ]
